site_name: LIKE ITN Open Science and FAIR principles
nav:
    - Introduction: 0_introduction.md
    - Research lifecycle: 1_research_lifecycle.md
    - Open Science principles: 2_open_science.md
    - The FAIR data principles: 3_fair_principles.md
    - The R<sup>5</sup> principles: 4_R5.md
    - How to apply these principles: 5_use_cases.md
    - Authors: authors.md
    - License: license.md

theme: readthedocs

markdown_extensions:
    - footnotes
